[phases.setup]
nixPkgs = ["python311", "gcc", "git"]

[phases.install]
cmds = ["python3.11 -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = ". /opt/venv/bin/activate && python3.11 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
